// Re-export shared types for backward compatibility
export type {
  TaskStatus,
  TaskPriority,
  Project,
  Task,
  TaskDependency,
  RecurringTaskTemplate,
  RecurrencePattern,
  RecurrenceConfig,
  ApiKey,
  CreateTaskInput,
  UpdateTaskInput,
  CreateProjectInput,
  UpdateProjectInput,
  CreateRecurringTemplateInput,
  UpdateRecurringTemplateInput,
  Sprint,
  SprintTask,
  VelocityMetric,
  SprintStatus,
  CreateSprintInput,
  UpdateSprintInput,
  AddTaskToSprintInput,
  UpdateSprintTaskInput,
} from '../shared/types'
